hash-format = "sha256"

[[files]]
file = "LICENSE"

[[files]]
file = "README.md"

[[files]]
file = "config/simple-rpc/server-entries.toml"

[[files]]
file = "config/simple-rpc/simple-rpc.toml"

[[files]]
file = "datapacks/custom.zip"

[[files]]
file = "mods/ad-astra-giselle-addon.pw.toml"
metafile = true

[[files]]
file = "mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/alexs-caves.pw.toml"
metafile = true

[[files]]
file = "mods/almost-unified.pw.toml"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "mods/applied-mekanistics.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
metafile = true

[[files]]
file = "mods/betterfarmland.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
metafile = true

[[files]]
file = "mods/botany-pots-tiers.pw.toml"
metafile = true

[[files]]
file = "mods/botany-pots.pw.toml"
metafile = true

[[files]]
file = "mods/botany-trees.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/chronon-technology.pw.toml"
metafile = true

[[files]]
file = "mods/chunk-loaders.pw.toml"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/cobblefordays.pw.toml"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
metafile = true

[[files]]
file = "mods/create-diesel-generators.pw.toml"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
metafile = true

[[files]]
file = "mods/create-jetpack.pw.toml"
metafile = true

[[files]]
file = "mods/create-misc-and-things.pw.toml"
metafile = true

[[files]]
file = "mods/create-molten-vents.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
metafile = true

[[files]]
file = "mods/create-utilities.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
metafile = true

[[files]]
file = "mods/cucumber.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/deeperdarker.pw.toml"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
metafile = true

[[files]]
file = "mods/effortless-building.pw.toml"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
metafile = true

[[files]]
file = "mods/enchanting-infuser.pw.toml"
metafile = true

[[files]]
file = "mods/enderio.pw.toml"
metafile = true

[[files]]
file = "mods/ends-delight.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/excavar.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-storage.pw.toml"
metafile = true

[[files]]
file = "mods/extreme-reactors.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/flux-networks.pw.toml"
metafile = true

[[files]]
file = "mods/funky-flora.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/immersiveengineering.pw.toml"
metafile = true

[[files]]
file = "mods/industrial-foregoing.pw.toml"
metafile = true

[[files]]
file = "mods/infinitewatersource.pw.toml"
metafile = true

[[files]]
file = "mods/interactive.pw.toml"
metafile = true

[[files]]
file = "mods/item-collectors.pw.toml"
metafile = true

[[files]]
file = "mods/itemlocks.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/just-enough-mekanism-multiblocks.pw.toml"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
metafile = true

[[files]]
file = "mods/mcjtylib.pw.toml"
metafile = true

[[files]]
file = "mods/mega.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-additions.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
metafile = true

[[files]]
file = "mods/merequester.pw.toml"
metafile = true

[[files]]
file = "mods/mob-lassos.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/my-server-is-compatible.pw.toml"
metafile = true

[[files]]
file = "mods/mystical-agradditions.pw.toml"
metafile = true

[[files]]
file = "mods/mystical-agriculture.pw.toml"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
metafile = true

[[files]]
file = "mods/nyctophobia.pw.toml"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/pipez.pw.toml"
metafile = true

[[files]]
file = "mods/pneumaticcraft-repressurized.pw.toml"
metafile = true

[[files]]
file = "mods/powah.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/rftools-base.pw.toml"
metafile = true

[[files]]
file = "mods/rftools-dimensions.pw.toml"
metafile = true

[[files]]
file = "mods/rftools-utility.pw.toml"
metafile = true

[[files]]
file = "mods/rubidium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/security-craft.pw.toml"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/tempad.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
metafile = true

[[files]]
file = "mods/tool-leveling.pw.toml"
metafile = true

[[files]]
file = "mods/trash-cans.pw.toml"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
metafile = true

[[files]]
file = "mods/wormhole.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "mods/zerocore.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/unity-dark-edition.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/unity.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/solas-shader.pw.toml"
metafile = true
