name = "Blueskies"
author = "HttpRafa & IceStorm"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "698d6b8daba6078cac38b1910a5f913b353e490c5b539a72722b44d4ca674fd1"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
