name = "Per Audacia Ad Astra"
author = "HttpRafa & IceStorm"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.79"

[options]
no-internal-hashes = true
