name = "Blueskies"
author = "HttpRafa & IceStorm"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13a00aa1e6d2a2affafb584e067130d96a56b803581827b313dc0135a68b11c0"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
